In [1]:
import pandas as pd
data = pd.read_csv('Bank_Personal_Loan_Modelling.csv')

In [2]:
data.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler

# Load data
data = pd.read_csv('Bank_Personal_Loan_Modelling.csv')

# Optional: Data preprocessing (handling missing values, encoding, etc.)

# Drop irrelevant columns
data.drop(['ID', 'ZIP Code'], axis=1, inplace=True)

# Splitting data into features and target
X = data.drop('Personal Loan', axis=1)
y = data['Personal Loan']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)

# Evaluation
print(classification_report(y_test, predictions))
print("Accuracy:", accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       910
           1       0.88      0.64      0.74        90

    accuracy                           0.96      1000
   macro avg       0.92      0.82      0.86      1000
weighted avg       0.96      0.96      0.96      1000

Accuracy: 0.96